Repository mini-sora/minisora, pull requests merged in 2024-03, with the labels that each got.

#106 [docs]: add and update conference name and year to each paper in README.md and README_EN.md
  README.md
  README_EN.md
Labels: documentation, help wanted

#115 [doc] add pr and issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: documentation, enhancement

#133 Update README.md
  README.md
Labels: good first PR

#162 [docs] add two survey papers to readme
  README.md
  README_EN.md
Labels: documentation

#165 [docs] add sora techrxiv paper and update hot news
  README.md
  README_EN.md
Labels: documentation

#170 [docs] Update the list of hot news and remove unnecessary para
  README.md
  README_EN.md
Labels: documentation, enhancement

#172 [docs] add three diff survey papers
  README.md
  README_EN.md
Labels: documentation

#219 [docs]: modify docs according to #217
  .github/pull_request_template.md
  README.md
  README_CN.md
  docs/CONTRIBUTING.md
  docs/CONTRIBUTING_EN.md
Labels: good first PR

#220 Update README.md
  README.md
Labels: good first PR

#221 Adding five papers to Security
  README.md
  README_CN.md
Labels: good first PR

#237 [Add] hpc Open-Sora project to repo's resources
  README.md
  README_CN.md
Labels: documentation

#247 [docs]: reformat docs
  .github/CONTRIBUTING.md
  .github/CONTRIBUTING_zh-CN.md
  .github/pull_request_template.md
  README.md
  README_zh-CN.md
  codes/README.md
  codes/README_zh-CN.md
  codes/pipeline/README.md
  codes/pipeline/README_zh-CN.md
  docs/HOT_NEWS_BASELINES_GUIDES.md
  docs/HOT_NEWS_BASELINES_GUIDES_zh-CN.md
  docs/README.md
  docs/README_zh-CN.md
  notes/README.md
  notes/README_zh-CN.md
Labels: good first PR

#250 Add new paper discussion && Fix some typo
  README.md
  README_zh-CN.md
  notes/README.md
  notes/README_zh-CN.md
Labels: documentation, good first PR

#252 [docs]Add ACL 2023 paper link to LAVIS resource documentation
  README.md
  README_zh-CN.md
Labels: documentation

#268 [docs] Add the paper and github link for stableaudio.Fix the bracket…
  README.md
  README_zh-CN.md
Labels: documentation

#307 [docs] Add videoMamba paper and github
  README.md
  README_zh-CN.md
Labels: documentation

#324 [docs] update README.md & README_zh-CN.md about audio papers
  README.md
  README_zh-CN.md
Labels: documentation

#332 [docs] update paper information in README.md & README_zh-CN.md
  README.md
  README_zh-CN.md
Labels: good first PR

#353 Adding new paper about ZigMa: a DiT-style mamba-based backbone for diffusion models.
  README.md
  README_zh-CN.md
Labels: good first PR
