Repository mini-sora/minisora, pull requests merged in 2024-02, with the labels that each got.

#31 add OpenDiT
  README_EN.md
Labels: documentation, good first issue, invalid

#53 add video generation paper SimDA
  README.md
  README_EN.md
Labels: documentation

#59 添加了 latte论文精读翻译 pdf 文件
  notes/latte论文精读翻译.pdf
Labels: good first issue

#61 add StableVideo and MovieChat
  README.md
Labels: good first PR

#68 add Latte.md
  README.md
  assets/Latte/Latte网络结构.png
  assets/Latte/S-AdaLN.png
  assets/Latte/T2V1.png
  assets/Latte/T2V2.png
  assets/Latte/ViT.png
  assets/Latte/patch_embedding.png
  assets/Latte/result.jpg
  assets/Latte/training_FVD.png
  assets/Latte/模型配置.png
  notes/Latte.md
  notes/README.md
Labels: good first PR

#72 add Large-DiT
  README.md
  README_EN.md
Labels: good first PR

#100 [docs]: fix spelling mistakes of OpenDiT title in README.md and README_EN.md
  README.md
  README_EN.md
Labels: documentation
